### ISSUE TITLE
Allow user to change colormap

### ISSUE THREAD

**Issue by kadrlica** [lsst/display_matplotlib#1]
Would it be possible to give the user control over the colormap used to display images? I see that this is currently set to [`cmap=pyplot.cm.gray`](https://github.com/lsst/display_matplotlib/blob/d076f1fb4d29987d637edbb2680bc64a89bab192/python/lsst/display/matplotlib/matplotlib.py#L285).

**Comment by jdswinbank** [comment]
Added to the LSST Jira system as DM-15182.

**Comment by jdswinbank** [comment]
Closed by #8.
